server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-server:5432/iwvgdb
    username: ${secrets.POSTGRES_USER}
    password: ${secrets.POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

