spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iwvgdb
    username: ${secrets.POSTGRES_USER}
    password: ${secrets.POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create / create-drop / update / none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"

logging:
  level:
    root: WARN
    es.upm.miw: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
